name: Deploy Theme

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    name: Push to Shopify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v7
        with:
          node-version: 20
      - name: Push theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_STORE: xpaw-maylyf4d.myshopify.com
        run: npx shopify theme push --theme 161599815785 --allow-live
